# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468a48e2cdfaa2ab303bd4f877246aacf3fef4bbfb857fbc651adcdac0baf1318c60f78010a692852010714c2913e44fc560451a6653d73f0ae10a540930b0ef
  smaxtec_api_email: <%= ENV["SMAXTEC_API_EMAIL"] %>
  smaxtec_api_password: <%= ENV["SMAXTEC_API_PASSWORD"] %>

test:
  secret_key_base: b6e8cadef5aba524553f1a284b69485f685c69c5a3225bb4c89f0e26ab6151bc34c9dc2a6bb1c4b0d5626088d764869367ec83143c22dfa48d73d2e47dea2438
  smaxtec_api_email: <%= ENV["SMAXTEC_API_EMAIL"] %>
  smaxtec_api_password: <%= ENV["SMAXTEC_API_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smaxtec_api_email: <%= ENV["SMAXTEC_API_EMAIL"] %>
  smaxtec_api_password: <%= ENV["SMAXTEC_API_PASSWORD"] %>
